# Generated by Django 5.2 on 2025-04-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_color',
            field=models.CharField(default='Black', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='default_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='M', max_length=10),
        ),
    ]
