# Generated by Django 5.2 on 2025-04-16 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='default_color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='default_size',
        ),
    ]
