# Generated by Django 5.2 on 2025-04-23 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('black', 'Black'), ('gray', 'Gray'), ('navy', 'Navy'), ('white', 'White'), ('beige', 'Beige')], default='black', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='M', max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='color',
            field=models.CharField(choices=[('black', 'Black'), ('gray', 'Gray'), ('navy', 'Navy'), ('white', 'White'), ('beige', 'Beige')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=10),
        ),
    ]
