# Generated by Django 5.2 on 2025-05-28 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_rename_image_product_main_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='main_image',
            new_name='image',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
